apiVersion: batch/v1
kind: Job
metadata:
  name: cpsecret
  namespace: smq-dev
spec:
  template:
    metadata:
      name: cpsecret
    spec:
      serviceAccountName: argocd-admin
      containers:
      - name: tester
        image: bitnami/kubectl
        command:
         - "bin/bash"
         - "-c"
         - "kubectl get get secret ibm-entitlement-key -n openshift-operators -o json | jq -r '.metadata.namespace=smq-dev' | oc apply -f -"
      restartPolicy: Never 