apiVersion: v1
kind: ServiceAccount
metadata:
  name: smq-job-sa
  namespace: smq-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secrets-to-sa
  namespace: smq-dev
subjects:
  - kind: ServiceAccount
    name: smq-job-sa
roleRef:
  kind: Role
  name: secret-mgr
  apiGroup: rbac.authorization.k8s.io  