apiVersion: v1
kind: ServiceAccount
metadata:
  name: smq-job-sa
  namespace: smq-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secrets-to-sa
subjects:
  - kind: ServiceAccount
    name: smq-job-sa
    namespace: smq-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
